import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * 
 */
public class View extends javax.swing.JFrame {
Connection c = null;
Statement s = null;
ResultSet r = null;
    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        addtf = new javax.swing.JLabel();
        ordertf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totaltf = new javax.swing.JLabel();
        pizzaamttf = new javax.swing.JLabel();
        snackstf = new javax.swing.JLabel();
        desserttf = new javax.swing.JLabel();
        nametf = new javax.swing.JLabel();
        drinkstf = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        typetf = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        numtf = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 550));
        getContentPane().setLayout(null);

        addtf.setBackground(new java.awt.Color(0, 0, 0));
        addtf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        addtf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(addtf);
        addtf.setBounds(140, 230, 220, 40);

        ordertf.setBackground(new java.awt.Color(0, 0, 0));
        ordertf.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ordertf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ordertf);
        ordertf.setBounds(290, 100, 140, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Order Number:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 270, 20);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 240, 110, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 190, 20);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pizza Amount:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 170, 170, 20);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Snacks Amount:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(380, 300, 190, 31);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 170, 90, 20);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Dessert Amount:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 370, 190, 31);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Drinks Amount:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 230, 190, 31);

        totaltf.setBackground(new java.awt.Color(0, 0, 0));
        totaltf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        totaltf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(totaltf);
        totaltf.setBounds(200, 370, 170, 40);

        pizzaamttf.setBackground(new java.awt.Color(0, 0, 0));
        pizzaamttf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        pizzaamttf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pizzaamttf);
        pizzaamttf.setBounds(550, 160, 130, 40);

        snackstf.setBackground(new java.awt.Color(0, 0, 0));
        snackstf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        snackstf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(snackstf);
        snackstf.setBounds(570, 300, 120, 40);

        desserttf.setBackground(new java.awt.Color(0, 0, 0));
        desserttf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        desserttf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(desserttf);
        desserttf.setBounds(570, 370, 110, 40);

        nametf.setBackground(new java.awt.Color(0, 0, 0));
        nametf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        nametf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nametf);
        nametf.setBounds(130, 170, 170, 30);

        drinkstf.setBackground(new java.awt.Color(0, 0, 0));
        drinkstf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        drinkstf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(drinkstf);
        drinkstf.setBounds(560, 230, 110, 30);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Amount:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 380, 170, 20);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Type:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 440, 90, 30);

        typetf.setBackground(new java.awt.Color(0, 0, 0));
        typetf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        typetf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(typetf);
        typetf.setBounds(120, 440, 160, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 90, 150, 30);

        numtf.setBackground(new java.awt.Color(0, 0, 0));
        numtf.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        numtf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(numtf);
        numtf.setBounds(220, 300, 150, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 10, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("view.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 0, 690, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Welcome().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        
        Class.forName("java.sql.Driver");
        c = DriverManager.getConnection("jdbc:mysql://localhost/pizza_paradise", "root", "12345");
        s = c.createStatement();
       String query1 = "Select*from customer where order_no = "+ Integer.parseInt(ordertf.getText())+";";
        r = s.executeQuery(query1);
        if(r.next()){
        String a,b,c;
        a = r.getString("name");
        b = r.getString("address"); 
        c = r.getString("contact");
        nametf.setText(a);
        addtf.setText(b);
        numtf.setText(c);
        
        String query2 = "Select*from order_details where order_no = "+ Integer.parseInt(ordertf.getText())+";";
        r = s.executeQuery(query2);
        if(r.next()){
        String d,e,f,g;
        d = r.getString("pizza_amt"); 
        e = r.getString("drinks_amt");
        f = r.getString("snacks_amt");
        g = r.getString("dessert_amt");
         pizzaamttf.setText(d);
        drinkstf.setText(e);
        snackstf.setText(f);
        desserttf.setText(g); }
        
        String query3 = "Select*from payment where order_no = "+ Integer.parseInt(ordertf.getText())+";";
        r = s.executeQuery(query3);
        if(r.next()){
         String h,i;
        h = r.getString("amount"); 
        i = r.getString("order_type");
         totaltf.setText(h);
        typetf.setText(i); }
      
        }
        else{
          JOptionPane.showMessageDialog(null, "No such Order Number exists");
        
        
    
}
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addtf;
    private javax.swing.JLabel desserttf;
    private javax.swing.JLabel drinkstf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel nametf;
    private javax.swing.JLabel numtf;
    private javax.swing.JTextField ordertf;
    private javax.swing.JLabel pizzaamttf;
    private javax.swing.JLabel snackstf;
    private javax.swing.JLabel totaltf;
    private javax.swing.JLabel typetf;
    // End of variables declaration//GEN-END:variables
}
